ml_best_hparams = [
    {
        "model": "CatBoost",
        "dataset": "tjh",
        "task": "outcome",
        "max_depth": 5,
        "n_estimators": 100,
        "learning_rate": 0.1,
        "batch_size": 81920,
        "main_metric": "auprc",
    },
    {
        "model": "DT",
        "dataset": "tjh",
        "task": "outcome",
        "max_depth": 10,
        "n_estimators": 100,
        "learning_rate": 1.0,
        "batch_size": 81920,
        "main_metric": "auprc",
    },
    {
        "model": "GBDT",
        "dataset": "tjh",
        "task": "outcome",
        "max_depth": 5,
        "n_estimators": 100,
        "learning_rate": 0.1,
        "batch_size": 81920,
        "main_metric": "auprc",
    },
    {
        "model": "RF",
        "dataset": "tjh",
        "task": "outcome",
        "max_depth": 10,
        "n_estimators": 100,
        "learning_rate": 0.1,
        "batch_size": 81920,
        "main_metric": "auprc",
    },
    {
        "model": "XGBoost",
        "dataset": "tjh",
        "task": "outcome",
        "max_depth": 5,
        "n_estimators": 100,
        "learning_rate": 0.1,
        "batch_size": 81920,
        "main_metric": "auprc",
    },
    {
        "model": "CatBoost",
        "dataset": "tjh",
        "task": "los",
        "max_depth": 5,
        "n_estimators": 100,
        "learning_rate": 0.1,
        "batch_size": 81920,
        "main_metric": "mae",
    },
    {
        "model": "DT",
        "dataset": "tjh",
        "task": "los",
        "max_depth": 5,
        "n_estimators": 50,
        "learning_rate": 0.1,
        "batch_size": 81920,
        "main_metric": "mae",
    },
    {
        "model": "GBDT",
        "dataset": "tjh",
        "task": "los",
        "max_depth": 5,
        "n_estimators": 100,
        "learning_rate": 0.1,
        "batch_size": 81920,
        "main_metric": "mae",
    },
    {
        "model": "RF",
        "dataset": "tjh",
        "task": "los",
        "max_depth": 15,
        "n_estimators": 50,
        "learning_rate": 1.0,
        "batch_size": 81920,
        "main_metric": "mae",
    },
    {
        "model": "XGBoost",
        "dataset": "tjh",
        "task": "los",
        "max_depth": 5,
        "n_estimators": 100,
        "learning_rate": 0.1,
        "batch_size": 81920,
        "main_metric": "mae",
    },
    {
        "model": "CatBoost",
        "dataset": "cdsl",
        "task": "outcome",
        "max_depth": 5,
        "n_estimators": 50,
        "learning_rate": 0.1,
        "batch_size": 81920,
        "main_metric": "auprc",
    },
    {
        "model": "DT",
        "dataset": "cdsl",
        "task": "outcome",
        "max_depth": 5,
        "n_estimators": 10,
        "learning_rate": 0.01,
        "batch_size": 81920,
        "main_metric": "auprc",
    },
    {
        "model": "GBDT",
        "dataset": "cdsl",
        "task": "outcome",
        "max_depth": 5,
        "n_estimators": 100,
        "learning_rate": 0.1,
        "batch_size": 81920,
        "main_metric": "auprc",
    },
    {
        "model": "RF",
        "dataset": "cdsl",
        "task": "outcome",
        "max_depth": 15,
        "n_estimators": 100,
        "learning_rate": 1.0,
        "batch_size": 81920,
        "main_metric": "auprc",
    },
    {
        "model": "XGBoost",
        "dataset": "cdsl",
        "task": "outcome",
        "max_depth": 5,
        "n_estimators": 50,
        "learning_rate": 0.1,
        "batch_size": 81920,
        "main_metric": "auprc",
    },
    {
        "model": "CatBoost",
        "dataset": "cdsl",
        "task": "los",
        "max_depth": 10,
        "n_estimators": 100,
        "learning_rate": 0.1,
        "batch_size": 81920,
        "main_metric": "mae",
    },
    {
        "model": "DT",
        "dataset": "cdsl",
        "task": "los",
        "max_depth": 5,
        "n_estimators": 50,
        "learning_rate": 0.01,
        "batch_size": 81920,
        "main_metric": "mae",
    },
    {
        "model": "GBDT",
        "dataset": "cdsl",
        "task": "los",
        "max_depth": 5,
        "n_estimators": 100,
        "learning_rate": 0.1,
        "batch_size": 81920,
        "main_metric": "mae",
    },
    {
        "model": "RF",
        "dataset": "cdsl",
        "task": "los",
        "max_depth": 15,
        "n_estimators": 100,
        "learning_rate": 1.0,
        "batch_size": 81920,
        "main_metric": "mae",
    },
    {
        "model": "XGBoost",
        "dataset": "cdsl",
        "task": "los",
        "max_depth": 10,
        "n_estimators": 50,
        "learning_rate": 0.1,
        "batch_size": 81920,
        "main_metric": "mae",
    },
]
